In [1]:
import pandas as pd

In [2]:
matches = pd.read_csv("matches.csv", index_col=0)
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,g/sh,fk,pk,pkatt,season,team
0,2023-08-12,15:00,Premier League,Matchweek 1,Sat,Home,W,4.0,1.0,Luton Town,...,Match Report,NaN,26.0,11.0,0.12,0.0,1.0,1.0,2024,Brighton and Hove Albion
1,2023-08-19,15:00,Premier League,Matchweek 2,Sat,Away,W,4.0,1.0,Wolves,...,Match Report,NaN,16.0,8.0,0.25,0.0,0.0,0.0,2024,Brighton and Hove Albion
1,2023-08-11,20:00,Premier League,Matchweek 1,Fri,Away,W,3.0,0.0,Burnley,...,Match Report,NaN,17.0,8.0,0.18,0.0,0.0,0.0,2024,Manchester City
3,2023-08-19,20:00,Premier League,Matchweek 2,Sat,Home,W,1.0,0.0,Newcastle Utd,...,Match Report,NaN,14.0,4.0,0.07,0.0,0.0,0.0,2024,Manchester City
1,2023-08-12,12:30,Premier League,Matchweek 1,Sat,Home,W,2.0,1.0,Nott'ham Forest,...,Match Report,NaN,15.0,7.0,0.13,0.0,0.0,0.0,2024,Arsenal

In [180]:
matches.columns

Index(['date', 'time', 'round', 'day', 'venue', 'result', 'gf', 'ga',
       'opponent', 'xg', 'xga', 'poss', 'captain', 'formation', 'referee',
       'sh', 'sot', 'g/sh', 'fk', 'pk', 'pkatt', 'season', 'team', 'target',
       'venue_code', 'opp_code', 'hour', 'day_code'],
      dtype='object')

In [3]:
matches.shape

(2320, 27)

In [9]:
3 * 20 *38 + (20 * 2)   #all matches in the 2021 - 2023 seasons and two matches in the 2024 season

2320

In [6]:
matches["season"].value_counts()

2023    760
2022    760
2021    760
2024     40
Name: season, dtype: int64

In [10]:
matches["team"].value_counts()   #Luton has just been promoted to the EPL

Chelsea                     117
Brighton and Hove Albion    116
Wolverhampton Wanderers     116
Arsenal                     116
Liverpool                   116
Tottenham Hotspur           116
West Ham United             116
Newcastle United            116
Aston Villa                 116
Crystal Palace              116
Manchester United           116
Manchester City             116
Everton                     116
Southampton                 114
Leeds United                114
Leicester City              114
Fulham                       78
Brentford                    78
Burnley                      77
Sheffield United             40
Bournemouth                  40
Nottingham Forest            40
Watford                      38
Norwich City                 38
West Bromwich Albion         38
Luton Town                    2
Name: team, dtype: int64

In [14]:
matches[matches["team"] == "Chelsea"].sort_values("season")

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,g/sh,fk,pk,pkatt,season,team
57,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Away,L,1.0,2.0,Aston Villa,...,Match Report,NaN,23.0,7.0,0.04,0.0,0.0,0.0,2021,Chelsea
23,2020-12-28,17:30,Premier League,Matchweek 16,Mon,Home,D,1.0,1.0,Aston Villa,...,Match Report,NaN,16.0,5.0,0.06,0.0,0.0,0.0,2021,Chelsea
22,2020-12-26,17:30,Premier League,Matchweek 15,Sat,Away,L,1.0,3.0,Arsenal,...,Match Report,NaN,18.0,2.0,0.06,1.0,0.0,1.0,2021,Chelsea
21,2020-12-21,20:00,Premier League,Matchweek 14,Mon,Home,W,3.0,0.0,West Ham,...,Match Report,NaN,11.0,7.0,0.27,0.0,0.0,0.0,2021,Chelsea
20,2020-12-15,18:00,Premier League,Matchweek 13,Tue,Away,L,1.0,2.0,Wolves,...,Match Report,NaN,13.0,3.0,0.08,1.0,0.0,0.0,2021,Chelsea
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28,2023-02-03,20:00,Premier League,Matchweek 22,Fri,Home,D,0.0,0.0,Fulham,...,Match Report,NaN,12.0,2.0,0.00,0.0,0.0,0.0,2023,Chelsea
39,2023-04-08,15:00,Premier League,Matchweek 30,Sat,Away,L,0.0,1.0,Wolves,...,Match Report,NaN,13.0,1.0,0.00,0.0,0.0,0.0,2023,Chelsea
2,2023-08-25,20:00,Premier League,Matchweek 3,Fri,Home,W,3.0,0.0,Luton Town,...,Match Report,NaN,19.0,8.0,0.16,1.0,0.0,0.0,2024,Chelsea
1,2023-08-20,16:30,Premier League,Matchweek 2,Sun,Away,L,1.0,3.0,West Ham,...,Match Report,NaN,16.0,3.0,0.06,0.0,0.0,1.0,2024,Chelsea
0,2023-08-13,16:30,Premier League,Matchweek 1,Sun,Home,D,1.0,1.0,Liverpool,...,Match Report,NaN,10.0,4.0,0.10,1.0,0.0,0.0,2024,Chelsea

In [13]:
matches["round"].value_counts()

Matchweek 1     80
Matchweek 2     78
Matchweek 3     62
Matchweek 32    60
Matchweek 23    60
Matchweek 12    60
Matchweek 24    60
Matchweek 25    60
Matchweek 26    60
Matchweek 27    60
Matchweek 29    60
Matchweek 30    60
Matchweek 22    60
Matchweek 33    60
Matchweek 34    60
Matchweek 28    60
Matchweek 35    60
Matchweek 36    60
Matchweek 37    60
Matchweek 31    60
Matchweek 21    60
Matchweek 7     60
Matchweek 11    60
Matchweek 4     60
Matchweek 5     60
Matchweek 6     60
Matchweek 8     60
Matchweek 9     60
Matchweek 10    60
Matchweek 13    60
Matchweek 20    60
Matchweek 14    60
Matchweek 15    60
Matchweek 16    60
Matchweek 17    60
Matchweek 18    60
Matchweek 19    60
Matchweek 38    60
Name: round, dtype: int64

In [15]:
matches.dtypes

date             object
time             object
comp             object
round            object
day              object
venue            object
result           object
gf              float64
ga              float64
opponent         object
xg              float64
xga             float64
poss            float64
attendance      float64
captain          object
formation        object
referee          object
match report     object
notes           float64
sh              float64
sot             float64
g/sh            float64
fk              float64
pk              float64
pkatt           float64
season            int64
team             object
dtype: object

In [16]:
del matches["comp"]

In [31]:
del matches["attendance", "match report", "notes"]

In [18]:
matches["date"] = pd.to_datetime(matches["date"])

In [19]:
matches["target"] = (matches["result"] == "W").astype("int")     #This assigns the resulting integer values to a new column named "target". Each element in the "target" column will be 1 if the corresponding match result is "W" (win) and 0 otherwise.

In [32]:
matches.tail()

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,referee,sh,sot,g/sh,fk,pk,pkatt,season,team,target
38,2021-05-02,19:15,Matchweek 34,Sun,Away,L,0.0,4.0,Tottenham,0.5,...,Andre Marriner,8.0,1.0,0.00,0.0,0.0,0.0,2021,Sheffield United,0
39,2021-05-08,15:00,Matchweek 35,Sat,Home,L,0.0,2.0,Crystal Palace,0.7,...,Simon Hooper,7.0,0.0,0.00,1.0,0.0,0.0,2021,Sheffield United,0
40,2021-05-16,19:00,Matchweek 36,Sun,Away,W,1.0,0.0,Everton,1.2,...,Jonathan Moss,10.0,3.0,0.10,0.0,0.0,0.0,2021,Sheffield United,1
41,2021-05-19,18:00,Matchweek 37,Wed,Away,L,0.0,1.0,Newcastle Utd,0.9,...,Robert Jones,11.0,1.0,0.00,1.0,0.0,0.0,2021,Sheffield United,0
42,2021-05-23,16:00,Matchweek 38,Sun,Home,W,1.0,0.0,Burnley,0.5,...,Kevin Friend,12.0,3.0,0.08,0.0,0.0,0.0,2021,Sheffield United,1

In [25]:
matches.columns

Index(['date', 'time', 'round', 'day', 'venue', 'result', 'gf', 'ga',
       'opponent', 'xg', 'xga', 'poss', 'attendance', 'captain', 'formation',
       'referee', 'match report', 'sh', 'sot', 'g/sh', 'fk', 'pk', 'pkatt',
       'season', 'team', 'target'],
      dtype='object')

In [33]:
matches["venue_code"] = matches["venue"].astype("category").cat.codes   #It assigns a numerical code to each unique value in the "venue" column.

In [34]:
matches["opp_code"] = matches["opponent"].astype("category").cat.codes   #It assigns a numerical code to each unique value in the "opponent" column.

In [35]:
matches["hour"] = matches["time"].str.replace(":.+", "", regex=True).astype("int")    #It extracts the hour part from the "time" column

In [36]:
matches["day_code"] = matches["date"].dt.dayofweek  #It extracts the day of the week from the "date" column

In [37]:
matches

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,fk,pk,pkatt,season,team,target,venue_code,opp_code,hour,day_code
0,2023-08-12,15:00,Matchweek 1,Sat,Home,W,4.0,1.0,Luton Town,4.0,...,0.0,1.0,1.0,2024,Brighton and Hove Albion,1,1,13,15,5
1,2023-08-19,15:00,Matchweek 2,Sat,Away,W,4.0,1.0,Wolves,2.2,...,0.0,0.0,0.0,2024,Brighton and Hove Albion,1,0,25,15,5
1,2023-08-11,20:00,Matchweek 1,Fri,Away,W,3.0,0.0,Burnley,1.9,...,0.0,0.0,0.0,2024,Manchester City,1,0,5,20,4
3,2023-08-19,20:00,Matchweek 2,Sat,Home,W,1.0,0.0,Newcastle Utd,1.0,...,0.0,0.0,0.0,2024,Manchester City,1,1,16,20,5
1,2023-08-12,12:30,Matchweek 1,Sat,Home,W,2.0,1.0,Nott'ham Forest,0.8,...,0.0,0.0,0.0,2024,Arsenal,1,1,18,12,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2021-05-02,19:15,Matchweek 34,Sun,Away,L,0.0,4.0,Tottenham,0.5,...,0.0,0.0,0.0,2021,Sheffield United,0,0,21,19,6
39,2021-05-08,15:00,Matchweek 35,Sat,Home,L,0.0,2.0,Crystal Palace,0.7,...,1.0,0.0,0.0,2021,Sheffield United,0,1,7,15,5
40,2021-05-16,19:00,Matchweek 36,Sun,Away,W,1.0,0.0,Everton,1.2,...,0.0,0.0,0.0,2021,Sheffield United,1,0,8,19,6
41,2021-05-19,18:00,Matchweek 37,Wed,Away,L,0.0,1.0,Newcastle Utd,0.9,...,1.0,0.0,0.0,2021,Sheffield United,0,0,16,18,2
42,2021-05-23,16:00,Matchweek 38,Sun,Home,W,1.0,0.0,Burnley,0.5,...,0.0,0.0,0.0,2021,Sheffield United,1,1,5,16,6

In [57]:
matches["target"].value_counts()

0    1421
1     899
Name: target, dtype: int64

In [49]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

In [39]:
# Define the parameter grid
param_grid = {
    'n_estimators': [50, 100, 200],
    'min_samples_split': [2, 5, 10],
    'max_depth': [None, 5, 10]
}

# Create the random forest classifier
rf = RandomForestClassifier(random_state=1)

In [43]:
train = matches[matches["date"] < '2023-01-01']
test = matches[matches["date"] > '2023-01-01']

In [46]:
# Calculate the percentage of train and test data
train_percent = (len(train) / len(matches)) * 100
test_percent = (len(test) / len(matches)) * 100

# Print the percentages
print("Train Data Percentage: {:.2f}%".format(train_percent))
print("Test Data Percentage: {:.2f}%".format(test_percent))     #studies show that the best results are obtained if we use 20-30% of the data for testing, and the remaining 70-80% of the data for training.

Train Data Percentage: 79.66%
Test Data Percentage: 20.17%

In [47]:
predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [50]:
# Perform grid search
grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, cv=5)
grid_search.fit(train[predictors], train["target"])

# Print the best parameters and best score
print("Best Parameters:", grid_search.best_params_)
print("Best Score:", grid_search.best_score_)

Best Parameters: {'max_depth': 5, 'min_samples_split': 2, 'n_estimators': 50}
Best Score: 0.6331165311653116

In [51]:
# Access the best model from grid search
best_model = grid_search.best_estimator_

# Make predictions using the best model
preds = best_model.predict(test[predictors])

In [52]:
from sklearn.metrics import accuracy_score
error = accuracy_score(test["target"], preds)
error

0.6132478632478633

In [53]:
combined = pd.DataFrame(dict(actual=test["target"], predicted=preds))

In [54]:
pd.crosstab(index=combined["actual"], columns=combined["predicted"])

predicted    0   1
actual
0          269  17
1          164  18

In [58]:
from sklearn.metrics import precision_score

precision_score(test["target"], preds)    #model correctly identifies around 51.43% of the positive predictions.

0.5142857142857142

**Another Feature Engineering for Model**

In [59]:
grouped_matches = matches.groupby("team")
group = grouped_matches.get_group("Manchester City").sort_values("date")  #groups the "matches" DF by team, selects a specific team's group

In [61]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group                   ##calculates rolling averages for specified columns, adds the rolling averages as new columns, removes rows with missing rolling average values, and returns the modified DataFrame.

In [162]:
cols = ["gf", "ga","xg"]    #, "fk", "pk", "pkatt"
new_cols = [f"{c}_rolling" for c in cols]

rolling_averages(group, cols, new_cols)

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,season,team,target,venue_code,opp_code,hour,day_code,gf_rolling,ga_rolling,xg_rolling
5,2020-10-17,17:30,Matchweek 5,Sat,Home,W,1.0,0.0,Arsenal,1.3,...,2021,Manchester City,1,1,0,17,5,2.000000,2.333333,1.333333
7,2020-10-24,12:30,Matchweek 6,Sat,Away,D,1.0,1.0,West Ham,1.0,...,2021,Manchester City,0,0,24,12,5,1.333333,2.000000,1.133333
9,2020-10-31,12:30,Matchweek 7,Sat,Away,W,1.0,0.0,Sheffield Utd,1.6,...,2021,Manchester City,1,0,19,12,5,1.000000,0.666667,1.166667
11,2020-11-08,16:30,Matchweek 8,Sun,Home,D,1.0,1.0,Liverpool,1.4,...,2021,Manchester City,0,1,12,16,6,1.000000,0.333333,1.300000
12,2020-11-21,17:30,Matchweek 9,Sat,Away,L,0.0,2.0,Tottenham,1.4,...,2021,Manchester City,0,0,21,17,5,1.000000,0.666667,1.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,2023-05-21,16:00,Matchweek 37,Sun,Home,W,1.0,0.0,Chelsea,1.2,...,2023,Manchester City,1,1,6,16,6,2.666667,0.333333,1.900000
57,2023-05-24,20:00,Matchweek 32,Wed,Away,D,1.0,1.0,Brighton,1.8,...,2023,Manchester City,0,0,4,20,2,2.000000,0.333333,1.533333
58,2023-05-28,16:30,Matchweek 38,Sun,Away,L,0.0,1.0,Brentford,1.6,...,2023,Manchester City,0,0,3,16,6,1.666667,0.333333,1.266667
1,2023-08-11,20:00,Matchweek 1,Fri,Away,W,3.0,0.0,Burnley,1.9,...,2024,Manchester City,1,0,5,20,4,0.666667,0.666667,1.533333
3,2023-08-19,20:00,Matchweek 2,Sat,Home,W,1.0,0.0,Newcastle Utd,1.0,...,2024,Manchester City,1,1,16,20,5,1.333333,0.666667,1.766667

In [163]:
matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))
matches_rolling                       #takes the rolling_averages function and applies to each team

                                 date   time         round  day venue result  \
team
Arsenal                 6  2020-10-04  14:00   Matchweek 4  Sun  Home      W
                        7  2020-10-17  17:30   Matchweek 5  Sat  Away      L
                        9  2020-10-25  19:15   Matchweek 6  Sun  Home      L
                        11 2020-11-01  16:30   Matchweek 7  Sun  Away      W
                        13 2020-11-08  19:15   Matchweek 8  Sun  Home      L
...                               ...    ...           ...  ...   ...    ...
Wolverhampton Wanderers 41 2023-05-13  15:00  Matchweek 36  Sat  Away      L
                        42 2023-05-20  15:00  Matchweek 37  Sat  Home      D
                        43 2023-05-28  16:30  Matchweek 38  Sun  Away      L
                        0  2023-08-14  20:00   Matchweek 1  Mon  Away      L
                        1  2023-08-19  15:00   Matchweek 2  Sat  Home      L

                             gf   ga         opponent   xg  ...  season  \
team                                                        ...
Arsenal                 6   2.0  1.0    Sheffield Utd  0.6  ...    2021
                        7   0.0  1.0  Manchester City  0.9  ...    2021
                        9   0.0  1.0   Leicester City  0.7  ...    2021
                        11  1.0  0.0   Manchester Utd  1.0  ...    2021
                        13  0.0  3.0      Aston Villa  1.5  ...    2021
...                         ...  ...              ...  ...  ...     ...
Wolverhampton Wanderers 41  0.0  2.0   Manchester Utd  0.3  ...    2023
                        42  1.0  1.0          Everton  1.6  ...    2023
                        43  0.0  5.0          Arsenal  0.5  ...    2023
                        0   0.0  1.0   Manchester Utd  2.2  ...    2024
                        1   1.0  4.0         Brighton  2.1  ...    2024

                                               team target venue_code  \
team
Arsenal                 6                   Arsenal      1          1
                        7                   Arsenal      0          0
                        9                   Arsenal      0          1
                        11                  Arsenal      1          0
                        13                  Arsenal      0          1
...                                             ...    ...        ...
Wolverhampton Wanderers 41  Wolverhampton Wanderers      0          0
                        42  Wolverhampton Wanderers      0          1
                        43  Wolverhampton Wanderers      0          0
                        0   Wolverhampton Wanderers      0          0
                        1   Wolverhampton Wanderers      0          1

                           opp_code  hour  day_code  gf_rolling  ga_rolling  \
team
Arsenal                 6        19    14         6    2.000000    1.333333
                        7        14    17         5    1.666667    1.666667
                        9        11    19         6    1.000000    1.666667
                        11       15    16         6    0.666667    1.000000
                        13        1    19         6    0.333333    0.666667
...                             ...   ...       ...         ...         ...
Wolverhampton Wanderers 41       15    15         5    1.000000    2.000000
                        42        8    15         5    0.333333    2.666667
                        43        0    16         6    0.666667    1.000000
                        0        15    20         0    0.333333    2.666667
                        1         4    15         5    0.333333    2.333333

                            xg_rolling
team
Arsenal                 6     1.433333
                        7     1.000000
                        9     0.933333
                        11    0.733333
                        13    0.866667
...                                ...
Wolverhampton Wanderers 41    1.000000
                        42    0.633333
                        43    0.900000
                        0     0.800000
                        1     1.433333

[2243 rows x 31 columns]

In [74]:
matches_rolling = matches_rolling.droplevel('team')
matches_rolling          #removes team as index

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,day_code,gf_rolling,ga_rolling,xga_rolling,sh_rolling,sot_rolling,g/sh_rolling,fk_rolling,pk_rolling,pkatt_rolling
6,2020-10-04,14:00,Matchweek 4,Sun,Home,W,2.0,1.0,Sheffield Utd,0.6,...,6,2.000000,1.333333,1.600000,8.000000,3.666667,0.256667,0.666667,0.000000,0.000000
7,2020-10-17,17:30,Matchweek 5,Sat,Away,L,0.0,1.0,Manchester City,0.9,...,5,1.666667,1.666667,1.633333,5.666667,3.666667,0.290000,0.000000,0.000000,0.000000
9,2020-10-25,19:15,Matchweek 6,Sun,Home,L,0.0,1.0,Leicester City,0.7,...,6,1.000000,1.666667,1.400000,7.000000,3.666667,0.193333,0.666667,0.000000,0.000000
11,2020-11-01,16:30,Matchweek 7,Sun,Away,W,1.0,0.0,Manchester Utd,1.0,...,6,0.666667,1.000000,0.733333,9.666667,4.000000,0.110000,1.000000,0.000000,0.000000
13,2020-11-08,19:15,Matchweek 8,Sun,Home,L,0.0,3.0,Aston Villa,1.5,...,6,0.333333,0.666667,0.800000,9.666667,2.666667,0.000000,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41,2023-05-13,15:00,Matchweek 36,Sat,Away,L,0.0,2.0,Manchester Utd,0.3,...,5,1.000000,2.000000,1.866667,8.000000,2.000000,0.056667,0.000000,0.333333,0.333333
42,2023-05-20,15:00,Matchweek 37,Sat,Home,D,1.0,1.0,Everton,1.6,...,5,0.333333,2.666667,2.666667,7.000000,1.333333,0.056667,0.000000,0.000000,0.000000
43,2023-05-28,16:30,Matchweek 38,Sun,Away,L,0.0,5.0,Arsenal,0.5,...,6,0.666667,1.000000,2.233333,8.000000,2.333333,0.083333,0.333333,0.000000,0.000000
0,2023-08-14,20:00,Matchweek 1,Mon,Away,L,0.0,1.0,Manchester Utd,2.2,...,0,0.333333,2.666667,2.666667,8.000000,1.666667,0.026667,0.666667,0.000000,0.000000
1,2023-08-19,15:00,Matchweek 2,Sat,Home,L,1.0,4.0,Brighton,2.1,...,5,0.333333,2.333333,2.333333,14.000000,3.666667,0.026667,0.666667,0.000000,0.000000

In [164]:
matches_rolling.columns

Index(['date', 'time', 'round', 'day', 'venue', 'result', 'gf', 'ga',
       'opponent', 'xg', 'xga', 'poss', 'captain', 'formation', 'referee',
       'sh', 'sot', 'g/sh', 'fk', 'pk', 'pkatt', 'season', 'team', 'target',
       'venue_code', 'opp_code', 'hour', 'day_code', 'gf_rolling',
       'ga_rolling', 'xg_rolling'],
      dtype='object')

In [165]:
new_cols

['gf_rolling', 'ga_rolling', 'xg_rolling']

In [166]:
predictors

['venue_code', 'opp_code', 'hour', 'day_code']

In [167]:
cols

['gf', 'ga', 'xg']

In [168]:
matches_rolling.index = range(matches_rolling.shape[0])

In [169]:
predictors_new= ["venue_code", "opp_code", "hour", "day_code", "sh", "sot"]
predictors_new

['venue_code', 'opp_code', 'hour', 'day_code', 'sh', 'sot']

In [170]:
def make_predictions(data, predictors_new):
    train = data[data["date"] < '2023-01-01']
    test = data[data["date"] > '2023-01-01']
    
    grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, cv=5)
    grid_search.fit(train[predictors_new], train["target"])
    best_model = grid_search.best_estimator_
   
    preds = best_model.predict(test[predictors_new])
    
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)
    error = precision_score(test["target"], preds)
    return combined, error

In [171]:
combined, error = make_predictions(matches_rolling, predictors_new + new_cols)
error

0.6013513513513513

In [172]:
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index=True, right_index=True)

#combined and matches_rolling are merged based on their index values. The resulting DataFrame contains columns from both DataFrames,

In [175]:
combined.head()

    actual  predicted       date     team        opponent result
89       0          1 2023-01-03  Arsenal   Newcastle Utd      D
90       1          1 2023-01-15  Arsenal       Tottenham      W
91       1          0 2023-01-22  Arsenal  Manchester Utd      W
92       0          0 2023-02-04  Arsenal         Everton      L
93       0          1 2023-02-11  Arsenal       Brentford      D

In [176]:
class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {"Brighton and Hove Albion": "Brighton", "Manchester United": "Manchester Utd", "Newcastle United": "Newcastle Utd", "Tottenham Hotspur": "Tottenham", "West Ham United": "West Ham", "Wolverhampton Wanderers": "Wolves"} 
mapping = MissingDict(**map_values)

In [177]:
combined["new_team"] = combined["team"].map(mapping)
merged = combined.merge(combined, left_on=["date", "new_team"], right_on=["date", "opponent"])

In [178]:
merged

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y
0,0,1,2023-01-03,Arsenal,Newcastle Utd,D,Arsenal,0,0,Newcastle United,Arsenal,D,Newcastle Utd
1,1,1,2023-01-15,Arsenal,Tottenham,W,Arsenal,0,1,Tottenham Hotspur,Arsenal,L,Tottenham
2,1,0,2023-01-22,Arsenal,Manchester Utd,W,Arsenal,0,0,Manchester United,Arsenal,L,Manchester Utd
3,0,0,2023-02-04,Arsenal,Everton,L,Arsenal,1,0,Everton,Arsenal,W,Everton
4,0,1,2023-02-11,Arsenal,Brentford,D,Arsenal,0,0,Brentford,Arsenal,D,Brentford
...,...,...,...,...,...,...,...,...,...,...,...,...,...
434,0,0,2023-05-13,Wolverhampton Wanderers,Manchester Utd,L,Wolves,1,1,Manchester United,Wolves,W,Manchester Utd
435,0,0,2023-05-20,Wolverhampton Wanderers,Everton,D,Wolves,0,1,Everton,Wolves,D,Everton
436,0,0,2023-05-28,Wolverhampton Wanderers,Arsenal,L,Wolves,1,1,Arsenal,Wolves,W,Arsenal
437,0,0,2023-08-14,Wolverhampton Wanderers,Manchester Utd,L,Wolves,1,0,Manchester United,Wolves,W,Manchester Utd
438,0,0,2023-08-19,Wolverhampton Wanderers,Brighton,L,Wolves,1,1,Brighton and Hove Albion,Wolves,W,Brighton

In [179]:
merged[(merged["predicted_x"] == 1) & (merged["predicted_y"] ==0)]["actual_x"].value_counts()

1    77
0    37
Name: actual_x, dtype: int64

Saving the Model

In [181]:
import joblib 
# Save the model as a pickle in a file 
joblib.dump(best_model, 'saved_football_prediction_model.pkl')

['saved_football_prediction_model.pkl']